import type { Metadata } from "next";
import "../styles/theme.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "KeyBrHero",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className=" font-mono h-full bg-blueDolphin-main">
        {children}
      </body>
    </html>
  );
}
