export const colorThemes = [
  { themeName: "8008" },
  { themeName: "80s after dark" },
  { themeName: "alduin" },
  { themeName: "arch" },
  { themeName: "aurora" },
  { themeName: "bento" },
  { themeName: "bliss" },
  { themeName: "blue dolphin" },
  { themeName: "frozen llama" },
  { themeName: "blueberry light" },
  { themeName: "bouquet" },
  { themeName: "copper" },
  { themeName: "cyberspace" },
  { themeName: "dark" },
  { themeName: "terra" },
  { themeName: "cheesecake" },
  { themeName: "dark" },
];

export const qwerty = [
  {
    firstRow: [
      { firstKey: "~", secondKey: "`" },
      { firstKey: "!", secondKey: "1" },
      { firstKey: "@", secondKey: "2" },
      { firstKey: "#", secondKey: "3" },
      { firstKey: "$", secondKey: "4" },
      { firstKey: "%", secondKey: "5" },
      { firstKey: "^", secondKey: "6" },
      { firstKey: "&", secondKey: "7" },
      { firstKey: "*", secondKey: "8" },
      { firstKey: "(", secondKey: "9" },
      { firstKey: ")", secondKey: "0" },
      { firstKey: "_", secondKey: "-" },
      { firstKey: "+", secondKey: "=" },
      { firstKey: "Backspace" },
    ],
    secondRow: [
      { firstKey: "Tab" },
      { firstKey: "Q" },
      { firstKey: "W" },
      { firstKey: "E" },
      { firstKey: "R" },
      { firstKey: "T" },
      { firstKey: "Y" },
      { firstKey: "U" },
      { firstKey: "I" },
      { firstKey: "O" },
      { firstKey: "P" },
      { firstKey: "{", secondKey: "[" },
      { firstKey: "}", secondKey: "]" },
      { firstKey: "|", secondKey: "/" },
    ],
    thirdRow: [
      { firstKey: "Caps Lock" },
      { firstKey: "A" },
      { firstKey: "S" },
      { firstKey: "D" },
      { firstKey: "F" },
      { firstKey: "G" },
      { firstKey: "H" },
      { firstKey: "J" },
      { firstKey: "K" },
      { firstKey: "L" },
      { firstKey: ":", secondKey: ";" },
      { firstKey: '"', secondKey: "'" },
      { firstKey: "Enter" },
    ],
    fourthRow: [
      { firstKey: "Shift" },
      { firstKey: "Z" },
      { firstKey: "X" },
      { firstKey: "C" },
      { firstKey: "V" },
      { firstKey: "B" },
      { firstKey: "N" },
      { firstKey: "M" },
      { firstKey: "<", secondKey: "," },
      { firstKey: ">", secondKey: "." },
      { firstKey: "?", secondKey: "/" },
      { label: "shift_2", firstKey: "Shift" },
    ],
    fifthRow: [
      { firstKey: "Crtl", label: "crtl_1" },
      { firstKey: "Alt" },
      { firstKey: "" },
      { firstKey: "Alt" },
      { firstKey: "Crtl", label: "crtl_2" },
    ],
  },
];

export const azerty = [
  {
    firstRow: [
      { firstKey: "²" },
      {
        firstKey: "1",
        secondKey: "&",
      },
      {
        firstKey: "2",
        seconKey: "É",
        thirdKey: "~",
      },
      {
        firstKey: "3",
        secondKey: '"',
        thirdKey: "#",
      },
      {
        firstKey: "4",
        secondKey: "'",
        thirdKey: "{",
      },
      {
        firstKey: "5",
        secondKey: "(",
        thirdKey: "[",
      },
      {
        firstKey: "6",
        secondKey: "-",
        thirdKey: "|",
      },
      {
        firstKey: "7",
        secondKey: "È",
        thirdKey: "`",
      },
      {
        firstKey: "8",
        secondKey: "_",
        thirdKey: "\\",
      },
      {
        firstKey: "9",
        secondKey: "ç",
        thirdKey: "^",
      },
      {
        firstKey: "0",
        seconKey: "À",
        thirdKey: "@",
      },
      {
        firstKey: "°",
        secondKey: ")",
        thirdKey: "]",
      },
      {
        firstKey: "+",
        seconKey: "=",
        thirdKey: "}",
      },
      { firstKey: "Backspace" },
    ],
    secondRow: [
      { firstKey: "Tab" },
      { firstKey: "A" },
      { firstKey: "Z" },
      { firstKey: "E", secondKey: "€" },
      { firstKey: "R" },
      { firstKey: "T" },
      { firstKey: "Y" },
      { firstKey: "U" },
      { firstKey: "I" },
      { firstKey: "O" },
      { firstKey: "P" },
      { firstKey: ":", secondKey: "^" },
      { firstKey: "£", secondKey: "$", thirdKey: "¤" },
      { firstKey: "Enter" },
    ],
    thirdRow: [
      { firstKey: "Caps Lock" },
      { firstKey: "Q" },
      { firstKey: "S" },
      { firstKey: "D" },
      { firstKey: "F" },
      { firstKey: "G" },
      { firstKey: "H" },
      { firstKey: "J" },
      { firstKey: "K" },
      { firstKey: "L" },
      { firstKey: "M" },
      { firstKey: "%", secondKey: "Ù" },
      { firstKey: "µ", secondKey: "*" },
      { firstKey: "" },
    ],
    fourthRow: [
      { label: "shift_1", firstKey: "Shift" },
      { firstKey: "<", secondKey: ">" },
      { firstKey: "W" },
      { firstKey: "X" },
      { firstKey: "C" },
      { firstKey: "V" },
      { firstKey: "B" },
      { firstKey: "N" },
      { firstKey: "?", secondKey: "," },
      { firstKey: ".", secondKey: ";" },
      { firstKey: "/", secondKey: ":" },
      { firstKey: "§", secondKey: "!" },
      { label: "shift_2", firstKey: "Shift" },
    ],
    fifthRow: [
      { firstKey: "Crtl", label: "crtl_1" },
      { firstKey: "Alt" },
      { firstKey: "" },
      { firstKey: "Alt" },
      { firstKey: "Crtl", label: "crtl_2" },
    ],
  },
];
