export const qwerty = [
  {
    firstRow: [
      { firstKey: "~", secondKey: "`" },
      { firstKey: "!", secondKey: "1" },
      { firstKey: "@", secondKey: "2" },
      { firstKey: "#", secondKey: "3" },
      { firstKey: "$", secondKey: "4" },
      { firstKey: "%", secondKey: "5" },
      { firstKey: "^", secondKey: "6" },
      { firstKey: "&", secondKey: "7" },
      { firstKey: "*", secondKey: "8" },
      { firstKey: "(", secondKey: "9" },
      { firstKey: ")", secondKey: "0" },
      { firstKey: "_", secondKey: "-" },
      { firstKey: "+", secondKey: "=" },
      { firstKey: "Backspace" },
    ],
    secondRow: [
      { firstKey: "Tab" },
      { firstKey: "Q" },
      { firstKey: "W" },
      { firstKey: "E" },
      { firstKey: "R" },
      { firstKey: "T" },
      { firstKey: "Y" },
      { firstKey: "U" },
      { firstKey: "I" },
      { firstKey: "O" },
      { firstKey: "P" },
      { firstKey: "{", secondKey: "[" },
      { firstKey: "}", secondKey: "]" },
      { firstKey: "|", secondKey: "/" },
    ],
    thirdRow: [
      { firstKey: "Caps Lock" },
      { firstKey: "A" },
      { firstKey: "S" },
      { firstKey: "D" },
      { firstKey: "F" },
      { firstKey: "G" },
      { firstKey: "H" },
      { firstKey: "J" },
      { firstKey: "K" },
      { firstKey: "L" },
      { firstKey: ":", secondKey: ";" },
      { firstKey: '"', secondKey: "'" },
      { firstKey: "Enter" },
    ],
    fourthRow: [
      { firstKey: "Shift" },
      { firstKey: "Z" },
      { firstKey: "X" },
      { firstKey: "C" },
      { firstKey: "V" },
      { firstKey: "B" },
      { firstKey: "N" },
      { firstKey: "M" },
      { firstKey: "<", secondKey: "," },
      { firstKey: ">", secondKey: "." },
      { firstKey: "?", secondKey: "/" },
      { label: "shift_2", firstKey: "Shift" },
    ],
    fifthRow: [
      { firstKey: "Crtl", label: "crtl_1" },
      { firstKey: "Alt" },
      { firstKey: "" },
      { firstKey: "Alt" },
      { firstKey: "Crtl", label: "crtl_2" },
    ],
  },
];

export const azerty = [
  {
    firstRow: [
      { firstKey: "²" },
      {
        firstKey: "1",
        secondKey: "&",
      },
      {
        firstKey: "2",
        seconKey: "É",
        thirdKey: "~",
      },
      {
        firstKey: "3",
        secondKey: '"',
        thirdKey: "#",
      },
      {
        firstKey: "4",
        secondKey: "'",
        thirdKey: "{",
      },
      {
        firstKey: "5",
        secondKey: "(",
        thirdKey: "[",
      },
      {
        firstKey: "6",
        secondKey: "-",
        thirdKey: "|",
      },
      {
        firstKey: "7",
        secondKey: "È",
        thirdKey: "`",
      },
      {
        firstKey: "8",
        secondKey: "_",
        thirdKey: "\\",
      },
      {
        firstKey: "9",
        secondKey: "ç",
        thirdKey: "^",
      },
      {
        firstKey: "0",
        seconKey: "À",
        thirdKey: "@",
      },
      {
        firstKey: "°",
        secondKey: ")",
        thirdKey: "]",
      },
      {
        firstKey: "+",
        seconKey: "=",
        thirdKey: "}",
      },
      { firstKey: "Backspace" },
    ],
    secondRow: [
      { firstKey: "Tab" },
      { firstKey: "A" },
      { firstKey: "Z" },
      { firstKey: "E", secondKey: "€" },
      { firstKey: "R" },
      { firstKey: "T" },
      { firstKey: "Y" },
      { firstKey: "U" },
      { firstKey: "I" },
      { firstKey: "O" },
      { firstKey: "P" },
      { firstKey: ":", secondKey: "^" },
      { firstKey: "£", secondKey: "$", thirdKey: "¤" },
      { firstKey: "Enter" },
    ],
    thirdRow: [
      { firstKey: "Caps Lock" },
      { firstKey: "Q" },
      { firstKey: "S" },
      { firstKey: "D" },
      { firstKey: "F" },
      { firstKey: "G" },
      { firstKey: "H" },
      { firstKey: "J" },
      { firstKey: "K" },
      { firstKey: "L" },
      { firstKey: "M" },
      { firstKey: "%", secondKey: "Ù" },
      { firstKey: "µ", secondKey: "*" },
      { firstKey: "" },
    ],
    fourthRow: [
      { label: "shift_1", firstKey: "Shift" },
      { firstKey: "<", secondKey: ">" },
      { firstKey: "W" },
      { firstKey: "X" },
      { firstKey: "C" },
      { firstKey: "V" },
      { firstKey: "B" },
      { firstKey: "N" },
      { firstKey: "?", secondKey: "," },
      { firstKey: ".", secondKey: ";" },
      { firstKey: "/", secondKey: ":" },
      { firstKey: "§", secondKey: "!" },
      { label: "shift_2", firstKey: "Shift" },
    ],
    fifthRow: [
      { firstKey: "Crtl", label: "crtl_1" },
      { firstKey: "Alt" },
      { firstKey: "" },
      { firstKey: "Alt" },
      { firstKey: "Crtl", label: "crtl_2" },
    ],
  },
];

export const themes = [
  {
    name: "8080",
    label: "_8008",
    colors: {
      main: "#333a45",
      primary: "#939eae",
      secondary: "#f44c7f",
      tertiary: "#2e343d",
      hover: "#e9ecf0",
    },
  },
  {
    name: "80s after dark",
    label: "afterDark",
    colors: {
      main: "#1b1d36",
      primary: "#99d6ea",
      secondary: "#fca6d1",
      tertiary: "#17182c",
      hover: "#e1e7ec",
    },
  },
  {
    name: "alduin",
    label: "alduin",
    colors: {
      main: "#1c1c1c",
      primary: "#444444",
      secondary: "#dfd7af",
      tertiary: "#242424",
      hover: "#f5f3ed",
    },
  },
  {
    name: "arch",
    label: "arch",
    colors: {
      main: "#0c0d11",
      primary: "#454864",
      secondary: "#7ebab5",
      tertiary: "#171a25",
      hover: "#f6f5f5",
    },
  },
  {
    name: "aurora",
    label: "aurora",
    colors: {
      main: "#011926",
      primary: "#245c69",
      secondary: "#00e980",
      tertiary: "#000c13",
      hover: "#fff",
    },
  },
  {
    name: "bento",
    label: "bento",
    colors: {
      main: "#2d394d",
      primary: "#4a768d",
      secondary: "#ff7a90",
      tertiary: "#263041",
      hover: "#fffaf8",
    },
  },
  {
    name: "bliss",
    label: "bliss",
    colors: {
      main: "#262727",
      primary: "#665957",
      secondary: "#f0d3c9",
      tertiary: "#343231",
      hover: "#fff",
    },
  },
  {
    name: "blue dolphin",
    label: "blueDolphin",
    colors: {
      main: "#003950",
      primary: "#00e4ff",
      secondary: "#ffcefb",
      tertiary: "#014961",
      hover: "#82eaff",
    },
  },
  {
    name: "blueberry light",
    label: "blueberryLight",
    colors: {
      main: "#dae0f5",
      primary: "#92a4be",
      secondary: "#506477",
      tertiary: "#c1c7df",
      hover: "#678198",
    },
  },
  {
    name: "bouquet",
    label: "bouquet",
    colors: {
      main: "#173f35",
      primary: "#408e7b",
      secondary: "#eaa09c",
      tertiary: "#1f4e43",
      hover: "#e9e0d2",
    },
  },
  {
    name: "copper",
    label: "copper",
    colors: {
      main: "#442f29",
      primary: "#7ebab5",
      secondary: "#b46a55",
      tertiary: "#50362e",
      hover: "#e7e0de",
    },
  },
  {
    name: "cyberspace",
    label: "cyberspace",
    colors: {
      main: "#181c18",
      primary: "#9578d3",
      secondary: "#00ce7c",
      tertiary: "#131613",
      hover: "#c2fbe1",
    },
  },
  {
    name: "dark",
    label: "dark",
    colors: {
      main: "#111111",
      primary: "#444444",
      secondary: "#eeeeee",
      tertiary: "#191919",
      hover: "#eee",
    },
  },
  {
    name: "terra",
    label: "terra",
    colors: {
      main: "#0c100e",
      primary: "#436029",
      secondary: "#89c559",
      tertiary: "#0f1d18",
      hover: "#f0edd1",
    },
  },
  {
    name: "cheesecake",
    label: "cheesecake",
    colors: {
      main: "#fdf0d5",
      primary: "#d91c81",
      secondary: "#8e2949",
      tertiary: "#f3e2bf",
      hover: "#3a3335",
    },
  },
  {
    name: "frozen",
    label: "frozen",
    colors: {
      main: "#9bf2ea",
      primary: "#b690fd",
      secondary: "#6d44a6",
      tertiary: "#7fe7dd",
      hover: "#ffffff",
    },
  },
];
