export const colorThemes = [
  { themeName: "8008" },
  { themeName: "80s after dark" },
  { themeName: "alduin" },
  { themeName: "arch" },
  { themeName: "aurora" },
  { themeName: "bento" },
  { themeName: "bliss" },
  { themeName: "blue dolphin" },
  { themeName: "frozen llama" },
  { themeName: "blueberry light" },
  { themeName: "bouquet" },
  { themeName: "copper" },
  { themeName: "cyberspace" },
  { themeName: "dark" },
  { themeName: "terra" },
  { themeName: "cheesecake" },
  { themeName: "dark" },
];

export const qwerty = [
  {
    firstRow: [
      { firstKey: "~", seconKey: "`", size: 1 },
      { firstKey: "!", seconKey: "1", size: 1 },
      { firstKey: "@", seconKey: "2", size: 1 },
      { firstKey: "#", seconKey: "3", size: 1 },
      { firstKey: "$", seconKey: "4", size: 1 },
      { firstKey: "%", seconKey: "5", size: 1 },
      { firstKey: "^", seconKey: "6", size: 1 },
      { firstKey: "&", seconKey: "7", size: 1 },
      { firstKey: "*", seconKey: "8", size: 1 },
      { firstKey: "(", seconKey: "9", size: 1 },
      { firstKey: ")", seconKey: "0", size: 1 },
      { firstKey: "_", seconKey: "-", size: 1 },
      { firstKey: "+", seconKey: "=", size: 1 },
      { firstKey: "Backspace", size: 2 },
    ],
    secondRow: [
      { firstKey: "Tab", size: 1.5 },
      { firstKey: "Q", size: 1 },
      { firstKey: "W", size: 1 },
      { firstKey: "E", size: 1 },
      { firstKey: "R", size: 1 },
      { firstKey: "T", size: 1 },
      { firstKey: "Y", size: 1 },
      { firstKey: "U", size: 1 },
      { firstKey: "I", size: 1 },
      { firstKey: "O", size: 1 },
      { firstKey: "P", size: 1 },
      { firstKey: "{", seconKey: "[", size: 1 },
      { firstKey: "}", seconKey: "]", size: 1 },
      { firstKey: "|", seconKey: "/", size: 1.5 },
    ],
    thirdRow: [
      { firstKey: "Caps Lock", size: 1.75 },
      { firstKey: "A", size: 1 },
      { firstKey: "S", size: 1 },
      { firstKey: "D", size: 1 },
      { firstKey: "F", size: 1 },
      { firstKey: "G", size: 1 },
      { firstKey: "H", size: 1 },
      { firstKey: "J", size: 1 },
      { firstKey: "K", size: 1 },
      { firstKey: "L", size: 1 },
      { firstKey: ":", seconKey: ";", size: 1 },
      { firstKey: '"', seconKey: "'", size: 1 },
      { firstKey: "Enter", size: 2.75 },
    ],
    fourthRow: [
      { firstKey: "Shift", size: 2.75 },
      { firstKey: "Z", size: 1 },
      { firstKey: "X", size: 1 },
      { firstKey: "C", size: 1 },
      { firstKey: "V", size: 1 },
      { firstKey: "B", size: 1 },
      { firstKey: "N", size: 1 },
      { firstKey: "M", size: 1 },
      { firstKey: "<", seconKey: ",", size: 1 },
      { firstKey: ">", seconKey: ".", size: 1 },
      { firstKey: "?", seconKey: "/", size: 1 },
      { label: "shift_2", firstKey: "Shift", size: 2.75 },
    ],
    fifthRow: [
      { firstKey: "Crtl", label: "crtl_1" },
      { firstKey: "Alt", size: 1.25 },
      { firstKey: "", size: 10 },
      { firstKey: "Alt", size: 1.25 },
      { firstKey: "Crtl", label: "crtl_2" },
    ],
  },
];
